### ISSUE TITLE
Missing information in Readme: bundler must be 1.17.1

### ISSUE THREAD

**Issue by jlusiardi** [gocd/api.go.cd#357]
Hi,

when trying to install middleman by executing `bundle install --path .bundle --binstubs` i need bundler in Version 1.17.2 (at least 2.0.2) does not work. Could you add this piece of information for ruby noobs?

Regards
Joachim

**Comment by arvindsv** [comment]
@jlusiardi Added that check in this commit: https://github.com/gocd/api.go.cd/commit/fae020e1a8003cab34c9b476a7da3d3ab5d71a07

Thank you!

**Comment by jlusiardi** [comment]
hey @arvindsv, 
i am not sure, but would this not allow bundler in version 2.0.2 as well? perhaps 1.17.1 < Version < 2 would be better?

**Comment by arvindsv** [comment]
@jlusiardi I tried it on Ruby 2.3.8 with Bundler 2.0.2. It showed me a warning:

```
middleman-core (4.1.9) has dependency bundler (~> 1.1), which is unsatisfied by the current bundler version 2.0.2, so the dependency is being ignored
```

... but then it went ahead and installed `middleman-core` gem and it worked. What happened when you tried it with `2.0.2`?

**Comment by jlusiardi** [comment]
ok, just tried to reproduce:

```
$ gem install --user bundler

Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Installing ri documentation for bundler-2.0.2
Done installing documentation for bundler after 2 seconds
1 gem installed
```
Seems I have version 2.0.2 installed now:
```
$bundler --version

Bundler version 2.0.2
```
On a fresh checkout of master:

```
$bundle install --path .bundle --binstubs

Traceback (most recent call last):
	2: from /home/jlusiardi/.gem/ruby/2.5.0/bin/bundle:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (1.17.2) required by your /home/jlusiardi/Documents/src/api.go.cd/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.2`
```

The installing version 1.17.2:

```
$gem install --user bundler:1.17.2

Fetching: bundler-1.17.2.gem (100%)
Successfully installed bundler-1.17.2
Parsing documentation for bundler-1.17.2
Installing ri documentation for bundler-1.17.2
Done installing documentation for bundler after 2 seconds
1 gem installed
```

Again installing stuff:

```
$bundle install --path .bundle --binstubs

Fetching gem metadata from https://rubygems.org/............
Fetching rake 12.3.2
Installing rake 12.3.2
Fetching i18n 0.7.0
Installing i18n 0.7.0
Fetching minitest 5.11.3
Installing minitest 5.11.3
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.5
Installing tzinfo 1.2.5
Fetching activesupport 4.2.11.1
Installing activesupport 4.2.11.1
Fetching public_suffix 3.1.1
Installing public_suffix 3.1.1
Fetching addressable 2.6.0
Installing addressable 2.6.0
Fetching execjs 2.7.0
Installing execjs 2.7.0
Fetching autoprefixer-rails 9.6.1
Installing autoprefixer-rails 9.6.1
Fetching aws-eventstream 1.0.3
Installing aws-eventstream 1.0.3
Fetching aws-partitions 1.189.0
Installing aws-partitions 1.189.0
Fetching aws-sigv4 1.1.0
Installing aws-sigv4 1.1.0
Fetching jmespath 1.4.0
Installing jmespath 1.4.0
Fetching aws-sdk-core 3.59.0
Installing aws-sdk-core 3.59.0
Fetching aws-sdk-kms 1.23.0
Installing aws-sdk-kms 1.23.0
Fetching aws-sdk-s3 1.45.0
Installing aws-sdk-s3 1.45.0
Fetching backports 3.15.0
Installing backports 3.15.0
Using bundler 1.17.2
Fetching coffee-script-source 1.12.2
Installing coffee-script-source 1.12.2
Fetching coffee-script 2.4.1
Installing coffee-script 2.4.1
Fetching sass 3.4.25
Installing sass 3.4.25
Fetching compass-import-once 1.0.5
Installing compass-import-once 1.0.5
Fetching concurrent-ruby 1.1.5
Installing concurrent-ruby 1.1.5
Fetching contracts 0.13.0
Installing contracts 0.13.0
Fetching dotenv 2.7.4
Installing dotenv 2.7.4
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extensions
Fetching em-websocket 0.5.1
Installing em-websocket 0.5.1
Fetching erubis 2.7.0
Installing erubis 2.7.0
Fetching fast_blank 1.0.0
Installing fast_blank 1.0.0 with native extensions
Fetching fastimage 2.1.5
Installing fastimage 2.1.5
Fetching ffi 1.11.1
Installing ffi 1.11.1 with native extensions
Fetching temple 0.8.1
Installing temple 0.8.1
Fetching tilt 1.4.1
Installing tilt 1.4.1
Fetching haml 5.1.1
Installing haml 5.1.1
Fetching hamster 3.0.0
Installing hamster 3.0.0
Fetching hashie 3.6.0
Installing hashie 3.6.0
Fetching kramdown 1.17.0
Installing kramdown 1.17.0
Fetching rb-fsevent 0.10.3
Installing rb-fsevent 0.10.3
Fetching rb-inotify 0.10.0
Installing rb-inotify 0.10.0
Fetching listen 3.0.8
Installing listen 3.0.8
Fetching memoist 0.16.0
Installing memoist 0.16.0
Fetching thor 0.20.3
Installing thor 0.20.3
Fetching middleman-cli 4.1.9
Installing middleman-cli 4.1.9
Fetching padrino-support 0.13.3.4
Installing padrino-support 0.13.3.4
Fetching padrino-helpers 0.13.3.4
Installing padrino-helpers 0.13.3.4
Fetching parallel 1.17.0
Installing parallel 1.17.0
Fetching rack 1.6.11
Installing rack 1.6.11
Fetching servolux 0.13.0
Installing servolux 0.13.0
Fetching uglifier 3.2.0
Installing uglifier 3.2.0
Fetching middleman-core 4.1.9
Installing middleman-core 4.1.9
Fetching middleman 4.1.9
Installing middleman 4.1.9
Fetching middleman-autoprefixer 2.10.1
Installing middleman-autoprefixer 2.10.1
Fetching middleman-gh-pages 0.3.1
Installing middleman-gh-pages 0.3.1
Fetching rack-livereload 0.3.17
Installing rack-livereload 0.3.17
Fetching middleman-livereload 3.4.6
Installing middleman-livereload 3.4.6
Fetching sprockets 3.6.2
Installing sprockets 3.6.2
Fetching middleman-sprockets 4.0.0
Installing middleman-sprockets 4.0.0
Fetching rouge 3.6.0
Installing rouge 3.6.0
Fetching middleman-syntax 3.2.0
Installing middleman-syntax 3.2.0
Fetching mime-types-data 3.2019.0331
Installing mime-types-data 3.2019.0331
Fetching mime-types 3.2.2
Installing mime-types 3.2.2
Fetching redcarpet 3.4.0
Installing redcarpet 3.4.0 with native extensions
Bundle complete! 13 Gemfile dependencies, 64 gems now installed.
Bundled gems are installed into `./.bundle`
```
This seems to work now. But next command fails:

```
$ bundle exec ./bin/middleman server

/home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/sitemap/resource.rb:88: warning: constant ::Fixnum is deprecated
Traceback (most recent call last):
	19: from ./bin/middleman:29:in `<main>'
	18: from ./bin/middleman:29:in `load'
	17: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-cli-4.1.9/bin/middleman:51:in `<top (required)>'
	16: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-cli-4.1.9/bin/middleman:51:in `new'
	15: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/application.rb:262:in `initialize'
	14: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/application.rb:262:in `new'
	13: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/extension_manager.rb:12:in `initialize'
	12: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:125:in `load_settings'
	11: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:125:in `each'
	10: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:127:in `block in load_settings'
	 9: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:91:in `load'
	 8: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/core_extensions/rendering.rb:11:in `block in <top (required)>'
	 7: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/core_extensions/rendering.rb:11:in `require'
	 6: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/renderers/coffee_script.rb:2:in `<top (required)>'
	 5: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/renderers/coffee_script.rb:2:in `require'
	 4: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
	 3: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
	 2: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
	 1: from /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
```

Not sure how to fix this though.

**Comment by ketan** [comment]
> /home/jlusiardi/Documents/src/api.go.cd/.bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)

You probably need to have nodejs installed.

**Comment by arvindsv** [comment]
@jlusiardi Yes, @ketan is right. You'll need to install nodejs. It is strange that it somehow works with 1.17.2, but I'm hesitant to say it's a problem with bundler 2.0.2. See this:

Install only bundler 2.0.2 inside a pristine Docker container:

```
$ docker run -it --rm=true ruby:2.5 bash

root@8b8cd87dab9e:/# gem install bundler
Fetching bundler-2.0.2.gem
Successfully installed bundler-2.0.2
1 gem installed

root@8b8cd87dab9e:/# bundler --version
Bundler version 2.0.2

root@8b8cd87dab9e:/# git clone https://github.com/gocd/api.go.cd
Cloning into 'api.go.cd'...
remote: Enumerating objects: 9336, done.
remote: Total 9336 (delta 0), reused 0 (delta 0), pack-reused 9336
Receiving objects: 100% (9336/9336), 3.39 MiB | 9.12 MiB/s, done.
Resolving deltas: 100% (5852/5852), done.
```

Run `bundle install`:

```
root@8b8cd87dab9e:/# cd api.go.cd/

root@8b8cd87dab9e:/api.go.cd# ls
CODE_OF_CONDUCT.md  CONTRIBUTING.md  Gemfile  Gemfile.lock  LICENSE  README.md	Rakefile  build_gocd_pipelines	config.rb  data  font-selection.json  lib  rakelib  source

root@8b8cd87dab9e:/api.go.cd# bundle install --path .bundle --binstubs
Fetching gem metadata from https://rubygems.org/............
Fetching rake 12.3.2
Installing rake 12.3.2
Fetching i18n 0.7.0
Installing i18n 0.7.0
Fetching minitest 5.11.3
Installing minitest 5.11.3
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.5
Installing tzinfo 1.2.5
Fetching activesupport 4.2.11.1
Installing activesupport 4.2.11.1
Fetching public_suffix 3.1.1
Installing public_suffix 3.1.1
Fetching addressable 2.6.0
Installing addressable 2.6.0
Fetching execjs 2.7.0
Installing execjs 2.7.0
Fetching autoprefixer-rails 9.6.1
Installing autoprefixer-rails 9.6.1
Fetching aws-eventstream 1.0.3
Installing aws-eventstream 1.0.3
Fetching aws-partitions 1.189.0
Installing aws-partitions 1.189.0
Fetching aws-sigv4 1.1.0
Installing aws-sigv4 1.1.0
Fetching jmespath 1.4.0
Installing jmespath 1.4.0
Fetching aws-sdk-core 3.59.0
Installing aws-sdk-core 3.59.0
Fetching aws-sdk-kms 1.23.0
Installing aws-sdk-kms 1.23.0
Fetching aws-sdk-s3 1.45.0
Installing aws-sdk-s3 1.45.0
Fetching backports 3.15.0
Installing backports 3.15.0
Using bundler 1.17.3
Fetching coffee-script-source 1.12.2
Installing coffee-script-source 1.12.2
Fetching coffee-script 2.4.1
Installing coffee-script 2.4.1
Fetching sass 3.4.25
Installing sass 3.4.25
Fetching compass-import-once 1.0.5
Installing compass-import-once 1.0.5
Fetching concurrent-ruby 1.1.5
Installing concurrent-ruby 1.1.5
Fetching contracts 0.13.0
Installing contracts 0.13.0
Fetching dotenv 2.7.4
Installing dotenv 2.7.4
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extensions
Fetching em-websocket 0.5.1
Installing em-websocket 0.5.1
Fetching erubis 2.7.0
Installing erubis 2.7.0
Fetching fast_blank 1.0.0
Installing fast_blank 1.0.0 with native extensions
Fetching fastimage 2.1.5
Installing fastimage 2.1.5
Fetching ffi 1.11.1
Installing ffi 1.11.1 with native extensions
Fetching temple 0.8.1
Installing temple 0.8.1
Fetching tilt 1.4.1
Installing tilt 1.4.1
Fetching haml 5.1.1
Installing haml 5.1.1
Fetching hamster 3.0.0
Installing hamster 3.0.0
Fetching hashie 3.6.0
Installing hashie 3.6.0
Fetching kramdown 1.17.0
Installing kramdown 1.17.0
Fetching rb-fsevent 0.10.3
Installing rb-fsevent 0.10.3
Fetching rb-inotify 0.10.0
Installing rb-inotify 0.10.0
Fetching listen 3.0.8
Installing listen 3.0.8
Fetching memoist 0.16.0
Installing memoist 0.16.0
Fetching thor 0.20.3
Installing thor 0.20.3
Fetching middleman-cli 4.1.9
Installing middleman-cli 4.1.9
Fetching padrino-support 0.13.3.4
Installing padrino-support 0.13.3.4
Fetching padrino-helpers 0.13.3.4
Installing padrino-helpers 0.13.3.4
Fetching parallel 1.17.0
Installing parallel 1.17.0
Fetching rack 1.6.11
Installing rack 1.6.11
Fetching servolux 0.13.0
Installing servolux 0.13.0
Fetching uglifier 3.2.0
Installing uglifier 3.2.0
Fetching middleman-core 4.1.9
Installing middleman-core 4.1.9
Fetching middleman 4.1.9
Installing middleman 4.1.9
Fetching middleman-autoprefixer 2.10.1
Installing middleman-autoprefixer 2.10.1
Fetching middleman-gh-pages 0.3.1
Installing middleman-gh-pages 0.3.1
Fetching rack-livereload 0.3.17
Installing rack-livereload 0.3.17
Fetching middleman-livereload 3.4.6
Installing middleman-livereload 3.4.6
Fetching sprockets 3.6.2
Installing sprockets 3.6.2
Fetching middleman-sprockets 4.0.0
Installing middleman-sprockets 4.0.0
Fetching rouge 3.6.0
Installing rouge 3.6.0
Fetching middleman-syntax 3.2.0
Installing middleman-syntax 3.2.0
Fetching mime-types-data 3.2019.0331
Installing mime-types-data 3.2019.0331
Fetching mime-types 3.2.2
Installing mime-types 3.2.2
Fetching redcarpet 3.4.0
Installing redcarpet 3.4.0 with native extensions
Bundle complete! 13 Gemfile dependencies, 64 gems now installed.
Bundled gems are installed into `./.bundle`
```

It does not work:

```
root@8b8cd87dab9e:/api.go.cd# bundle exec ./bin/middleman server
/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/sitemap/resource.rb:88: warning: constant ::Fixnum is deprecated
bundler: failed to load command: ./bin/middleman (./bin/middleman)
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
  /api.go.cd/.bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
  /api.go.cd/.bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
  /api.go.cd/.bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
  /api.go.cd/.bundle/ruby/2.5.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
  /api.go.cd/.bundle/ruby/2.5.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/renderers/coffee_script.rb:2:in `require'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/renderers/coffee_script.rb:2:in `<top (required)>'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/core_extensions/rendering.rb:11:in `require'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/core_extensions/rendering.rb:11:in `block in <top (required)>'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:91:in `load'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:127:in `block in load_settings'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:125:in `each'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/extensions.rb:125:in `load_settings'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/extension_manager.rb:12:in `initialize'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/application.rb:262:in `new'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/application.rb:262:in `initialize'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-cli-4.1.9/bin/middleman:51:in `new'
  /api.go.cd/.bundle/ruby/2.5.0/gems/middleman-cli-4.1.9/bin/middleman:51:in `<top (required)>'
  /api.go.cd/bin/middleman:29:in `load'
  /api.go.cd/bin/middleman:29:in `<top (required)>'
```

Install nodejs:

```
root@8b8cd87dab9e:/api.go.cd# apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:2 http://deb.debian.org/debian buster InRelease [118 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [46.8 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [42.5 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7897 kB]
Fetched 8143 kB in 2s (4672 kB/s)
Reading package lists... Done

root@8b8cd87dab9e:/api.go.cd# apt-get install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libc-ares2 libnode64 libuv1 nodejs-doc
Suggested packages:
  npm
The following NEW packages will be installed:
  libc-ares2 libnode64 libuv1 nodejs nodejs-doc
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 6753 kB of archives.
After this operation, 30.4 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://deb.debian.org/debian buster/main amd64 libc-ares2 amd64 1.14.0-1 [85.8 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libuv1 amd64 1.24.1-1 [110 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 libnode64 amd64 10.15.2~dfsg-2 [5521 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 nodejs amd64 10.15.2~dfsg-2 [86.2 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 nodejs-doc all 10.15.2~dfsg-2 [950 kB]
Fetched 6753 kB in 1s (9918 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libc-ares2:amd64.
(Reading database ... 23978 files and directories currently installed.)
Preparing to unpack .../libc-ares2_1.14.0-1_amd64.deb ...
Unpacking libc-ares2:amd64 (1.14.0-1) ...
Selecting previously unselected package libuv1:amd64.
Preparing to unpack .../libuv1_1.24.1-1_amd64.deb ...
Unpacking libuv1:amd64 (1.24.1-1) ...
Selecting previously unselected package libnode64:amd64.
Preparing to unpack .../libnode64_10.15.2~dfsg-2_amd64.deb ...
Unpacking libnode64:amd64 (10.15.2~dfsg-2) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_10.15.2~dfsg-2_amd64.deb ...
Unpacking nodejs (10.15.2~dfsg-2) ...
Selecting previously unselected package nodejs-doc.
Preparing to unpack .../nodejs-doc_10.15.2~dfsg-2_all.deb ...
Unpacking nodejs-doc (10.15.2~dfsg-2) ...
Setting up libc-ares2:amd64 (1.14.0-1) ...
Setting up libuv1:amd64 (1.24.1-1) ...
Setting up libnode64:amd64 (10.15.2~dfsg-2) ...
Setting up nodejs-doc (10.15.2~dfsg-2) ...
Setting up nodejs (10.15.2~dfsg-2) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
Processing triggers for libc-bin (2.28-10) ...
```

Now it runs:

```
root@8b8cd87dab9e:/api.go.cd# bundle exec ./bin/middleman server
/api.go.cd/.bundle/ruby/2.5.0/gems/middleman-core-4.1.9/lib/middleman-core/sitemap/resource.rb:88: warning: constant ::Fixnum is deprecated
/api.go.cd/.bundle/ruby/2.5.0/gems/sprockets-3.6.2/lib/sprockets/digest_utils.rb:47: warning: constant ::Fixnum is deprecated
/api.go.cd/.bundle/ruby/2.5.0/gems/sprockets-3.6.2/lib/sprockets/digest_utils.rb:51: warning: constant ::Bignum is deprecated
/api.go.cd/.bundle/ruby/2.5.0/gems/sprockets-3.6.2/lib/sprockets/processor_utils.rb:110: warning: constant ::Fixnum is deprecated
/api.go.cd/.bundle/ruby/2.5.0/gems/sprockets-3.6.2/lib/sprockets/processor_utils.rb:111: warning: constant ::Bignum is deprecated
== The Middleman is loading
== LiveReload accepting connections from ws://172.17.0.2:35729
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"
```
